### ISSUE TITLE
使用FantasyZoneApi报错

### ISSUE THREAD

**Issue by AnyMoonS** [bloodyrabbit/mirai-setu#20]
随机报错，时不时正常
信息如下
2021-05-22 13:59:26 E/main: Exception in coroutine <unnamed>
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 31: Expected string literal but 'null' literal was found.
Use 'coerceInputValues = true' in 'Json {}` builder to coerce nulls to default values.
JSON input: .....
    "id": null,
    "title": null,
    "description": null,.....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:338)
        at kotlinx.serialization.json.internal.JsonReader.takeStringQuoted(JsonReader.kt:166)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:213)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeStringElement(AbstractDecoder.kt:58)
        at cn.blrabbit.mirai.setu.FantasyZoneResponse$$serializer.deserialize(FantasyZoneResponse.kt)
        at cn.blrabbit.mirai.setu.FantasyZoneResponse$$serializer.deserialize(FantasyZoneResponse.kt:6)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at cn.blrabbit.mirai.setu.FantasyZoneRequester.requestSetu(FantasyZoneRequester.kt:156)
        at cn.blrabbit.mirai.setu.FantasyZoneRequester$requestSetu$1.invokeSuspend(FantasyZoneRequester.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by AnyMoonS** [comment]
追加一条
搜图api设置FantasyZone会导致任何关键词都提示“未搜索到图片”

**Comment by bloodyrabbit** [comment]
收到，抱歉最近在忙毕业论文，没有及时回复。

**Comment by bloodyrabbit** [comment]
以修复此bug，抱歉，最近忙碌，新版本上线过于草率，没做测试
