### ISSUE TITLE
报错提示

### ISSUE THREAD

**Issue by LemonPAKA** [bloodyrabbit/mirai-setu#28]
出现错误, 请联系管理员检查后台或重试
Unexpected JSON token at offset 332: Encountered an unknown key 'ext'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.

控制台日志：
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)

	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)

	at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:333)

	at kotlinx.serialization.json.internal.JsonReader.fail$default(JsonReader.kt:332)

	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:145)

	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:88)

	at moe.ruabbit.mirai.setu.LoliconResponse$SetuImageInfo$$serializer.deserialize(LoliconResponse.kt:12)

	at moe.ruabbit.mirai.setu.LoliconResponse$SetuImageInfo$$serializer.deserialize(LoliconResponse.kt:12)

	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)

	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)

	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)

	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)

	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:479)

	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)

	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)

	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)

	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)

	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)

	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)

	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)

	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:72)

	at moe.ruabbit.mirai.setu.LoliconResponse$$serializer.deserialize(LoliconResponse.kt:5)

	at moe.ruabbit.mirai.setu.LoliconResponse$$serializer.deserialize(LoliconResponse.kt:5)

	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)

	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)

	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)

	at moe.ruabbit.mirai.setu.LoliconRequester.parseSetu(LoliconRequester.kt:218)

	at moe.ruabbit.mirai.setu.LoliconRequester.requestSetu(LoliconRequester.kt:35)

	at moe.ruabbit.mirai.setu.LoliconRequester$requestSetu$1.invokeSuspend(LoliconRequester.kt)

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)

	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)

	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)

	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)

	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)

	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)

	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)

	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)

	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)

	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)

	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)

	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)

	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)

	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)

	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)

	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)

	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)

	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by li14300** [comment]
目前看来是lolicon的作者在返回的json里加了'ext'和'uploadDate'字段，插件处理不了这俩字段，所以产生了报错

**Comment by li14300** [comment]
作者把这俩加上去的参数又给删了，又能用了。。。

**Comment by bloodyrabbit** [comment]
的确这样😂

**Comment by bloodyrabbit** [comment]
我现在测试是没问题的，还报这样的错误吗

**Comment by li14300** [comment]
现在不报错了，不过还是建议改一下，不知道作者以后还会不会把字段加上
