### ISSUE TITLE
请问为什么我用mcl加载这个插件总会报错啊

### ISSUE THREAD

**Issue by xxxxxxxxzq** [bloodyrabbit/mirai-setu#7]
2021-02-24 18:29:46 E/Mirai-setu: net.mamoe.yamlkt.YamlDecodingException: There must be a COLON between class key and value but found STRING for 'setu-config' masterid: 0 ^ at line 2, column 10 net.mamoe.yamlkt.YamlDecodingException: There must be a COLON between class key and value but found STRING for 'setu-config' masterid: 0 ^ at line 2, column 10 at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154) at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source) at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException$default(ContextualException.kt:128) at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException$default(Unknown Source) at net.mamoe.yamlkt.internal.YamlDecoder$BlockClassDecoder.decodeElementIndex(YamlDecoder.kt:279) at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:75) at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:47) at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:151) at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:39) at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConfig(AbstractJvmPlugin.kt:58) at com.blrabbit.mirai.MiraiSetuMain.onEnable(MiraiSetuMain.kt:45) at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113) at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119) at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt) at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36) at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129) at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172) at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:202) at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209) at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153) at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152) at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.base/java.lang.reflect.Method.invoke(Unknown Source) at org.itxtech.mcl.Utility.bootMirai(Utility.java:76) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.base/java.lang.reflect.Method.invoke(Unknown Source) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138) at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226) at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692) at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013) at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578) at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107) at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43) at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155) at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105) at org.mozilla.javascript.Context.call(Context.java:554) at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522) at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105) at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126) at com.sun.proxy.$Proxy4.run(Unknown Source) at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101) at org.itxtech.mcl.Loader.start(Loader.java:129) at org.itxtech.mcl.Loader.main(Loader.java:53)
环境是mcl1.0.5，32位jre11，安装了Onebot和mirai native

**Comment by bloodyrabbit** [comment]
Yaml解码错误，可能是配置文件除了问题。删除目录下的config/Mirai-setu，然后重新运行让插件重新生成配置文件。
建议修改使用vs code之类的文本编辑器，不要使用记事本，记事本有时候会往配置文件增加一些数据导致读取错误

**Comment by xxxxxxxxzq** [comment]
> Yaml解码错误，可能是配置文件除了问题。删除目录下的config/Mirai-setu，然后重新运行让插件重新生成配置文件。
> 建议修改使用vs code之类的文本编辑器，不要使用记事本，记事本有时候会往配置文件增加一些数据导致读取错误

谢谢大佬，问题解决了。那么我载入以后该如何使用这个插件呢？我在群里直接输入 - 色图时间  没有反应。

**Comment by bloodyrabbit** [comment]
管理员或缺机器是配置文件里面配置的管理员在群内输入青少年模式 青壮年模式 混合模式，这三个指令对应着三个模式。就可以开启插件

**Comment by xxxxxxxxzq** [comment]
> 管理员或缺机器是配置文件里面配置的管理员在群内输入青少年模式 青壮年模式 混合模式，这三个指令对应着三个模式。就可以开启插件

噢，原来是不加 - 的。。。

**Comment by bloodyrabbit** [comment]
那个 - 是Yaml的数组格式
